#!/usr/bin/env python3
"""Stability-first DRL-backbone ImageNet-32 diagnostic manifest."""

from __future__ import annotations

import argparse
import csv
from pathlib import Path


PROJECT_DIR = Path("/lus/eagle/projects/lc-mpi/Zhiqing/polaris_ebm")
DATA_DIR = Path("/eagle/lc-mpi/Zhiqing/polaris_ebm/data/imagenet32")

FIELDS = [
    "phase",
    "group",
    "exp_id",
    "benchmark",
    "model_family",
    "story",
    "train_mode",
    "world_size",
    "pipe_stages",
    "K",
    "steps",
    "lr",
    "lr_warmup_steps",
    "step_size",
    "noise_std",
    "sampler_prime",
    "sampler_temperature",
    "energy_loss_scale",
    "weight_mode",
    "last2_beta",
    "seed",
    "num_nodes",
    "ppn",
    "batch_size",
    "save_every",
    "vis_every",
    "eval_images",
    "queue",
    "train_walltime",
    "data_dir",
    "config",
    "clamp_x",
    "skip_optimizer_until_full_diagonal",
    "max_grad_norm",
    "grad_clip_norm",
    "diagnostic_first_steps",
    "diagnostic_log_every",
    "crash_abs_energy",
    "crash_max_abs_chain_unclamped",
    "crash_grad_norm",
    "soft_abs_energy",
    "soft_grad_norm",
    "hard_grad_norm",
    "clip_active_fraction",
    "soft_guard_stop",
    "submit",
    "notes",
]


def _row(
    *,
    phase: str,
    exp_id: str,
    train_mode: str,
    config: str,
    lr: str,
    step_size: str,
    noise_std: str,
    lr_warmup_steps: str = "0",
    sampler_prime: str = "0.0",
    sampler_temperature: str = "1.0",
    energy_loss_scale: str = "1.0",
    weight_mode: str = "uniform",
    pipe_stages: int = 1,
    steps: str = "500",
    skip_optimizer_until_full_diagonal: bool = False,
    max_grad_norm: str = "0.0",
    grad_clip_norm: str = "",
    soft_guard_stop: bool = False,
    submit: str = "no",
    notes: str = "",
) -> dict[str, str]:
    return {
        "phase": phase,
        "group": "imagenet32_drl_stability",
        "exp_id": exp_id,
        "benchmark": "imagenet32",
        "model_family": "drl_resnet_energy",
        "story": "stability-first restart for DRL backbone with the existing completion-aware objective",
        "train_mode": train_mode,
        "world_size": "4",
        "pipe_stages": str(int(pipe_stages)),
        "K": "100",
        "steps": str(steps),
        "lr": lr,
        "lr_warmup_steps": str(lr_warmup_steps),
        "step_size": step_size,
        "noise_std": noise_std,
        "sampler_prime": str(sampler_prime),
        "sampler_temperature": str(sampler_temperature),
        "energy_loss_scale": str(energy_loss_scale),
        "weight_mode": weight_mode,
        "last2_beta": "0.01",
        "seed": "1",
        "num_nodes": "1",
        "ppn": "4",
        "batch_size": "128",
        "save_every": "500",
        "vis_every": "500",
        "eval_images": "5000",
        "queue": "preemptable",
        "train_walltime": "02:00:00",
        "data_dir": str(DATA_DIR),
        "config": str(PROJECT_DIR / config),
        "clamp_x": "true",
        "skip_optimizer_until_full_diagonal": "true" if skip_optimizer_until_full_diagonal else "false",
        "max_grad_norm": str(max_grad_norm),
        "grad_clip_norm": grad_clip_norm,
        "diagnostic_first_steps": "200",
        "diagnostic_log_every": "50",
        "crash_abs_energy": "1000.0",
        "crash_max_abs_chain_unclamped": "2.5",
        "crash_grad_norm": "10000.0",
        "soft_abs_energy": "10.0",
        "soft_grad_norm": "100.0",
        "hard_grad_norm": "500.0",
        "clip_active_fraction": "0.25",
        "soft_guard_stop": "true" if soft_guard_stop else "false",
        "submit": submit,
        "notes": notes,
    }


def build_stability_rows() -> list[dict[str, str]]:
    return [
        _row(
            phase="A_ddp_reference",
            exp_id="imagenet32_drl_stability_A_ddp_moderate_s500",
            train_mode="ddp_fullk",
            pipe_stages=1,
            weight_mode="deep_only",
            config="configs/imagenet32_drl_stability_ddp.yaml",
            lr="5e-5",
            step_size="0.005",
            noise_std="0.005",
            notes="DDP full-K reference; clamp_x enabled.",
        ),
        _row(
            phase="B_pipeline_moderate",
            exp_id="imagenet32_drl_stability_B_pipe_p4_equal_moderate_s500",
            train_mode="pipe_strict",
            pipe_stages=4,
            weight_mode="uniform",
            config="configs/imagenet32_drl_stability_pipe_p4_equal_moderate.yaml",
            lr="5e-5",
            step_size="0.005",
            noise_std="0.005",
            skip_optimizer_until_full_diagonal=True,
            notes="Pipeline P4 equal moderate restart.",
        ),
        _row(
            phase="C_pipeline_conservative",
            exp_id="imagenet32_drl_stability_C_pipe_p4_equal_conservative_s500",
            train_mode="pipe_strict",
            pipe_stages=4,
            weight_mode="uniform",
            config="configs/imagenet32_drl_stability_pipe_p4_equal_conservative.yaml",
            lr="2.5e-5",
            step_size="0.002",
            noise_std="0.005",
            skip_optimizer_until_full_diagonal=True,
            notes="Pipeline P4 equal conservative restart.",
        ),
        _row(
            phase="D_deepest_control",
            exp_id="imagenet32_drl_stability_D_pipe_p4_deepest_moderate_s500",
            train_mode="pipe_strict",
            pipe_stages=4,
            weight_mode="deep_only",
            config="configs/imagenet32_drl_stability_pipe_p4_deep_moderate.yaml",
            lr="5e-5",
            step_size="0.005",
            noise_std="0.005",
            skip_optimizer_until_full_diagonal=True,
            notes="Deepest-only control to isolate equal-weight shallow-stage instability.",
        ),
        _row(
            phase="E_safest_fallback",
            exp_id="imagenet32_drl_stability_E_pipe_p4_equal_safest_s500",
            train_mode="pipe_strict",
            pipe_stages=4,
            weight_mode="uniform",
            config="configs/imagenet32_drl_stability_pipe_p4_equal_safest.yaml",
            lr="1e-5",
            step_size="0.001",
            noise_std="0.002",
            skip_optimizer_until_full_diagonal=True,
            grad_clip_norm="10.0",
            notes="Safest fallback; only path with explicit gradient clipping.",
        ),
        _row(
            phase="S1_prime_calibration",
            exp_id="imagenet32_drl_s1_ddp_prime10_scale1_s2k",
            train_mode="ddp_fullk",
            pipe_stages=1,
            weight_mode="deep_only",
            config="configs/imagenet32_drl_port_sanity_ddp_2k.yaml",
            steps="2000",
            lr="1e-7",
            lr_warmup_steps="10000",
            step_size="0.0005",
            noise_std="0.0005",
            sampler_prime="10",
            energy_loss_scale="1.0",
            max_grad_norm="0.0",
            grad_clip_norm="1.0",
            submit="yes",
            notes="DDP-only prime calibration; no recovery likelihood; very weak sampler drift.",
        ),
        _row(
            phase="S1_prime_calibration",
            exp_id="imagenet32_drl_s1_ddp_prime50_scale1_s2k",
            train_mode="ddp_fullk",
            pipe_stages=1,
            weight_mode="deep_only",
            config="configs/imagenet32_drl_port_sanity_ddp_2k.yaml",
            steps="2000",
            lr="1e-7",
            lr_warmup_steps="10000",
            step_size="0.0005",
            noise_std="0.0005",
            sampler_prime="50",
            energy_loss_scale="1.0",
            max_grad_norm="0.0",
            grad_clip_norm="1.0",
            submit="yes",
            notes="DDP-only prime calibration; no recovery likelihood.",
        ),
        _row(
            phase="S1_prime_calibration",
            exp_id="imagenet32_drl_s1_ddp_prime100_scale1_s2k",
            train_mode="ddp_fullk",
            pipe_stages=1,
            weight_mode="deep_only",
            config="configs/imagenet32_drl_port_sanity_ddp_2k.yaml",
            steps="2000",
            lr="1e-7",
            lr_warmup_steps="10000",
            step_size="0.0005",
            noise_std="0.0005",
            sampler_prime="100",
            energy_loss_scale="1.0",
            max_grad_norm="0.0",
            grad_clip_norm="1.0",
            submit="yes",
            notes="DDP-only prime calibration; no recovery likelihood.",
        ),
        _row(
            phase="S1_prime_calibration",
            exp_id="imagenet32_drl_s1_ddp_prime500_scale1_s2k",
            train_mode="ddp_fullk",
            pipe_stages=1,
            weight_mode="deep_only",
            config="configs/imagenet32_drl_port_sanity_ddp_2k.yaml",
            steps="2000",
            lr="1e-7",
            lr_warmup_steps="10000",
            step_size="0.0005",
            noise_std="0.0005",
            sampler_prime="500",
            energy_loss_scale="1.0",
            max_grad_norm="0.0",
            grad_clip_norm="1.0",
            submit="yes",
            notes="DDP-only prime calibration; closest to but below legacy implied prime.",
        ),
        _row(
            phase="S1_prime_calibration",
            exp_id="imagenet32_drl_s1_ddp_prime500_scale01_s2k",
            train_mode="ddp_fullk",
            pipe_stages=1,
            weight_mode="deep_only",
            config="configs/imagenet32_drl_port_sanity_ddp_2k.yaml",
            steps="2000",
            lr="1e-7",
            lr_warmup_steps="10000",
            step_size="0.0005",
            noise_std="0.0005",
            sampler_prime="500",
            energy_loss_scale="0.1",
            max_grad_norm="0.0",
            grad_clip_norm="1.0",
            submit="yes",
            notes="DDP-only combined sampler prime and loss-scale calibration.",
        ),
    ]


def write_manifest(path: str | Path, rows: list[dict[str, str]] | None = None) -> None:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = rows if rows is not None else build_stability_rows()
    with path.open("w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=FIELDS)
        writer.writeheader()
        for row in payload:
            writer.writerow(row)


def main() -> None:
    parser = argparse.ArgumentParser("Write ImageNet-32 DRL stability diagnostic manifest")
    parser.add_argument(
        "--output",
        default=str(PROJECT_DIR / "experiments" / "imagenet32_drl_stability_manifest.csv"),
    )
    args = parser.parse_args()
    rows = build_stability_rows()
    write_manifest(args.output, rows)
    print(f"wrote {len(rows)} rows to {args.output}")


if __name__ == "__main__":
    main()
